#!/usr/bin/env bash
set -e

nix run --extra-experimental-features nix-command --extra-experimental-features flakes github:nix-community/home-manager/release-25.05 -- --extra-experimental-features nix-command --extra-experimental-features flakes  switch --flake \#$USER@$(hostname)
